version: '3.8'

services:
  purocheck-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Set at least one of these API keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Required for OpenAI models
      - GROQ_API_KEY=${GROQ_API_KEY}      # Required for Groq models
      - GEMINI_API_KEY=${GEMINI_API_KEY}  # Required for Google Gemini models
    volumes:
      # Mount data directory for document uploads
      - ./data:/app/data
      # Mount chroma_db for persistence
      - ./chroma_db:/app/chroma_db
      # Mount checklist directory
      - ./checklist:/app/checklist
    command: ["python", "-m", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - purocheck-api
  #   restart: unless-stopped
